GROUP_REPOS = [
{
    "name": "Gorillaerne",
    "gitLinks": ["https://github.com/Gorillaerne/Devops_Gorillas"],
    "backend": "https://gorillahub.dk",
    "frontend": "https://gorillahub.dk",
    "monitoring": "https://monitor.gorillahub.dk",
    "stack": ["Go","Gorilla/Mux","JavaScript","HTML","CSS","Docker","Nginx"],
    "documentation": [],
    "sla": "",
},
{
    "name": "EmperiaPizza",
    "gitLinks": ["https://github.com/EmperiaPizza/EmperiaSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "ASCDevOps",
    "gitLinks": ["https://github.com/ASCDevOps/ASC_whoknows"],
    "backend": "https://ascsearch.dk",
    "frontend": "https://ascsearch.dk",
    "monitoring": "http://188.166.19.130:3000",
    "stack": ["GO", "PostGres","Docker","Nginx","Certbot","Prometheus","Alertmanager","Grafana"],
    "documentation": ["https://github.com/ASCDevOps/ASC_whoknows/tree/master/documentation"],
    "sla": "https://github.com/ASCDevOps/ASC_whoknows/blob/master/documentation/Service%20Level%20Agreement%20(SLA)/ASCSearch_SLA.pdf",
}, 
{
    "name": "ripmarkus",
    "gitLinks": ["https://github.com/ripmarkus/whoknows_ripmarkus"],
    "backend": "http://91.100.1.101",
    "frontend": "http://91.100.1.101",
    "monitoring": "https://monitoring.mathiasmortensen.dk/",
    "stack": ["Ruby", "SQLite"],
    "documentation": [],
    "sla": "",
},
{
    "name": "nasOps",
    "gitLinks": ["https://github.com/nasOps/MonkKnows"],
    "backend": "https://monkknows.dk",
    "frontend": "https://monkknows.dk",
    "monitoring": "http://20.91.203.235:3000",
    "stack": ["Ruby", "Sinatra", "PostgreSQL", "Nginx", "Azure VM", "Docker", "GitHub Actions", "Let's Encrypt", "Prometheus", "Grafana", "Azure Function", "One.com", "Postman", "SonarCloud"],
    "documentation": ["https://github.com/nasOps/MonkKnows/tree/main/docs"],
    "sla": "https://github.com/nasOps/MonkKnows/blob/main/docs/sla.md",
},
{
    "name": "BaseJumpers",
    "gitLinks": ["https://github.com/BaseJumpers/BaseJumperSearch"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
    "name": "Knowledgeables",
    "gitLinks": ["https://github.com/Knowledgeables/Knowledge"],
    "backend": "https://www.knowledgeable.one",
    "frontend": "https://www.knowledgeable.one",
    "monitoring": "http://20.100.172.127/",
    "stack": ["Golang","Nginx", "Azure VM", "SQLlite, Docker, Knex.js, Certbot, Terraform, Ansible, Prometheus, Grafana, Loki,  Resend"],
    "documentation": [],
    "sla": "https://docs.google.com/document/d/1NhLQFGPfJCcwER58Z1wSI9g0LqDIFZJsppy_SH0HaXc/edit?usp=sharing",
},
{
    "name": "team36",
    "gitLinks": ["https://github.com/DevOps-team36/legacy-whoknows"],
    "backend": "https://huw.dk",
    "frontend": "https://huw.dk",
    "monitoring": "https://monitor.huw.dk",
    "stack": ["Go", "Ansible", "PostgreSQL", "Nginx", "Prometheus", "Grafana", "Loki", "Docker", "Terraform", "Cloudflare", "Azure functions", "Postman", "Coderabbit"],
    "documentation": [],
    "sla": "",
},
{
    "name": "deploying-on-friday",
    "gitLinks": ["https://github.com/deploying-on-friday/dof"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
{
     "name": "SyntaxDevOpsSquad",
      "gitLinks": ["https://github.com/SyntaxDevopsSquad-SDS/devops-syntaxsquad"],
      "backend": "https://syntax-reborndev.com/",
      "frontend": "https://syntax-reborndev.com/",
      "monitoring": "https://monitor.syntax-reborndev.com/",
      "stack": ["GO", "PostgreSQL", "Prometheus", "Grafana", "Terraform", "Ansible", "Azure", "Digital Ocean","One.com", "Cloudflare", "Docker", "Nginx"],
      "documentation": ["https://github.com/SyntaxDevopsSquad-SDS/docs"],
      "sla": "https://github.com/SyntaxDevopsSquad-SDS/devops-syntaxsquad/tree/main/docs",
}  
]

